### ISSUE TITLE
Bug after reconnect

### ISSUE THREAD

**Issue by tututumuru** [Visecy/Karuha#19]
Hi, thanks for the project.

I found a serious error in your code.

This line stores `self.token` (https://github.com/Visecy/Karuha/blob/master/karuha/bot.py#L210), which is then used to create a new session (suppose we lost the connection and want to restore it).

type of `ctrl.params[‘token’]` is raw bytes. But `params[‘token’]` after pydantic is str with base64 (lol).

And now let's look at this line https://github.com/Visecy/Karuha/blob/master/karuha/bot.py#L176 which is used when reconnecting.

In the current code we get bytes (but it's ascii base64). Although tinode server expects raw bytes from us, which it passed from the beginning.

As a result, we have a reconnect error (401).

What do you think? I fixed it via `b64decode(self.token)`. Perhaps it is more correct to store `ctrl.params[‘token’]` instead of `params[‘token’]` in self.token.

Anyway, this is a very strange behaviour. Either I didn't follow the tinode code changes.

**Comment by Ovizro** [comment]
Hello, thank you for your issue.

This is indeed a very serious problem and it is reproducible. I will fix this problem in the next version.

> Perhaps it is more correct to store `ctrl.params[‘token’]` instead of `params[‘token’]` in self.token.

As for ctrl.params['token'], it cannot be used directly as a token because it is a JSON bytes. Pydantic only does the work of decoding JSON here.

**Comment by Ovizro** [comment]
You can now test whether the code in the dev branch works properly in your environment. If everything works well, I will release a new version.
