### ISSUE TITLE
Skip subscription when getting user information

### ISSUE THREAD

**Issue by tututumuru** [Visecy/Karuha#22]
Hello 👋

https://github.com/Visecy/Karuha/blob/master/karuha/event/bot.py#L378

In this code we can see the logic - if a user sends a status online, we subscribe to him. And if the user leaves, we soft unsubscribe.

But this approach creates side effects. When we are in the same group (bot and user), tinode also sends pres about online. And accordingly the bot creates a p2p topic (msg.src == usrXXXXXXX — the user we are in the group with).

As a result, in the UI we see an empty p2p chat that appeared “suddenly”.

UPD1:
My hypothesis:
1. When the bot appeared in the same group as the user, it was automatically added to “contacts” (subs)
2. Next, the user goes online and the bot gets pres {msg.topic == “me”, msg.src == “<USER_IN_GROUP_NOT_P2P>”, what == ON} 

This is very strange that if you are in the same group with a user, he is automatically your sub. I don't think telegram or whatsapp adds people in the group to contacts.

**Comment by tututumuru** [comment]
And about this:

```
        elif msg.what == pb.ServerPres.ACS:
            topic = msg.src
            _, meta = await self.bot.get(topic, "desc")
            if meta:
                await self.bot.set(topic, sub=pb.SetSub(mode=meta.desc.acs.given))
```

Is it right to get msg.src instead of msg.topic 🤔

In my case:
```
in: pres {
    what: ACS
    src: "usraNBJBbrKOX8" |  
    topic: "grp6qCbnCBPrgo" | 
    ...
    actor_user_id (missing from documentation)

    want: "JRWPS"
    given: "JRWPS"
}
```

If it's not too much trouble for you, you can tell the back story of pres handlers. What is each type assigned to?

**Comment by Ovizro** [comment]
Hi,

There is a very simple explanation for this problem. The chatbot will **only** process pres messages from the `me` topic. So for a group, the chatbot will only subscribe to the group itself when the group is online instead of subscribing to the members.

> As a result, in the UI we see an empty p2p chat that appeared “suddenly”.

I cannot reproduce the problem mentioned here on my Tinode server. If you can reproduce it, please provide the version information of Tinode server, Python and KaruhaBot and the complete DEBUG level log when the problem occurs.

**Comment by Ovizro** [comment]
> I was calling `get_user_desc` to get information about a user. But at the same time I didn't plan to subscribe to him. This method calls `ensure_sub`

Getting user information without subscription is indeed a requirement. I tried to compare the `desc` data in the meta under subscription and unsubscription, and only the data associated with p2p topic such as `acs` and `seqId` were different. I will consider changing the implementation of `get_user_desc` and adding related control flags to the upper-level functions.

Thank you very much for your reminder.

**Comment by Ovizro** [comment]
I have refactored the data module in the `dev` branch. Now when getting user or topic information, it will not try to actively subscribe to it. If you have free time, I hope you can do a simple test of these interfaces. If they do not meet your needs well, please continue to give me feedback.
