### ISSUE TITLE
Potential undefined behavior

### ISSUE THREAD

**Issue by tututumuru** [Visecy/Karuha#25]
https://github.com/Visecy/Karuha/blob/master/karuha/event/message.py#L61

Adding await here will allow us to control the sequence of actions (now the call is actually undefined due to the lack of await).

It might be more correct to write it like this:
```
await event.bot.note_read(event.topic, event.seq_id)
await MessageEvent.from_data_event(event).trigger(return_exceptions=True)
```

We first mark that the bot has read the message. Then we call the client implementation.

**Comment by Ovizro** [comment]
I don’t think strict ordering is needed here, `note_read` only provides read information, it can be parallelized with message processing to reduce the chatbot’s response time.

**Comment by tututumuru** [comment]
Yes, I agree. I will close this issue
