### ISSUE TITLE
Some bug after reconnect 2

### ISSUE THREAD

**Issue by tututumuru** [Visecy/Karuha#28]
It seems to me that there is an mistake contained here. I'm reserching it now.

https://github.com/Visecy/Karuha/blob/master/karuha/event/bot.py#L31

After reconnecting, my custom `on_rule` method either doesn't work or is duplicated. Maybe you have an idea what's wrong?

Maybe here:
- https://github.com/Visecy/Karuha/blob/master/karuha/bot.py#L1391
- https://github.com/Visecy/Karuha/blob/master/karuha/bot.py#L1297

**Comment by Ovizro** [comment]
When the bot reconnects, all tasks related to the bot will be terminated. This does not affect the registered `on_rule` dispatcher. If you find related problems, please provide code that can reproduce the problem and debug-level logs.
