### ISSUE TITLE
开发命令模块内容

### ISSUE THREAD

**Issue by 2021112806** [Visecy/Karuha#3]
我想参与开发命令模块中的内容，请问我能做一些什么呢？

**Comment by Ovizro** [comment]
可以考虑进行session部分的开发

session是命令模块的核心组件之一，用于存储命令会话信息，并提供与事件及其他底层模块的接口。

此部分开发至少需要实现以下功能：
1. 信息存储：保存本次会话所在的topic及用户信息
2. 事件接口：提供public, subscribe, leave事件的上层接口，并默认填入会话绑定数据

以下是可选的扩展功能：
3. 会话消息存储：记录属于本次会话的消息内容
4. 富文本接口：提供发送图片，文件，确认消息等常用富文本组件接口
5. 消息读取接口：提供等待消息返回接口，此部分需要配套实现Adaptor组件

关于Adaptor组件：
Adaptor仅作为暂用名，因为它并不是一个标准意义的适配器，它由一个抽象基类和一个事件处理器组成。抽象基类提供一个消息匹配接口和一个执行接口。当收到消息时，Adaptor事件处理器会遍历所有Adaptor，并执行其中消息匹配读最高的Adaptor实例。

关于以上内容，是否有疑问？

________________________________
From: 2021112806 ***@***.***>
Sent: Friday, November 17, 2023 8:10:46 PM
To: Visecy/Karuha ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Visecy/Karuha] 开发命令模块内容 (Issue #3)


我想参与开发命令模块中的内容，请问我能做一些什么呢？

―

**Comment by 2021112806** [comment]
好的😊

**Comment by Ovizro** [comment]
是否希望继续进行，请在三天内进行回复，否则此issue将被关闭
